blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Menuist Official Website
    url: https://wangchujiang.com/rightmenu-master/
    about: Introduction to the Menuist app on the official website!