blank_issues_enabled: false
contact_links:
  - name: ğŸŒ RightMenu Master Official Website
    url: https://wangchujiang.com/rightmenu-master/
    about: Introduction to the RightMenu Master app on the official website!